name: My First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "first step"
      - name: Print Good bye
        run: echo "Done last runner"
